### ISSUE TITLE
Background music doesn't play in Firefox

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/ludum-35#2]
This error is logged in the console: 
```[Error] : Unable to decode ./snd/backingTrack.wav this browser may not fully support this format, or the file may be corrupt, if this is an mp3 try removing id3 tags and album art from the file.```

Browser: Firefox 45.0.2
OS: Windows 10

**Comment by jedeen** [comment]
I set mp3 to the default as a quick fix for this problem.

**Comment by eonarheim** [comment]
@jedeen interesting, did we originally have just a wav? or was it a wav and an mp3 originally?

I thought we tested this in Firefox...

**Comment by jedeen** [comment]
@eonarheim I think we started with .wav files, and added .mp3 files at the end for IE support. The background music was set too low compared to the sound effects. Once I fixed that problem, this problem became apparent.
